# Numpy Assignment  

In [11]:
#Q1). Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#A1). NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python. Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries solidifies its position as the cornerstone of numerical computing in Python


In [1]:
#Q2). Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


#A2). In NumPy, both np.mean() and np.average() are used to compute the average of an array's elements, but they have some key differences in functionality:

### np.mean()

In [9]:
# np.mean() calculates the the arithmetic mean (average) of array along a specified axis.
# Synthax:- np.mean(a, axis = None, dtype = None, out = None)
# Usage:- Use np.mean() when you want to calculate the simple arithmetic mean without considering different weights for the elements.

### np.average()

In [10]:
# np.average() computes the weighted average of the array elements. If now weights are specified ,it behaves like np.mean()
# Synthax:- np.average(a, axis = None, weights = None, returned = None)
# Usage:- Use np.average() when you need to compute a weighted average, where some elements contribute more to the final average than others.

### When to Use One Over the Other?

In [8]:
# np.mean():
# When you need the simple arithmetic mean without any weights. 
# Example: Calculating the average of temperatures recorded over a week.

# np.average():
# When calculating a weighted average, especially if different elements have different levels of importance.
# Example: Calculating the average score of a student where different assignments have different weightage.

In [12]:
#Q3). Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

#A3). Reversing a NumPy array involves rearranging its elements in reverse order. Depending on the dimensionality of the array (1D, 2D, etc.), you can reverse the array along different axes. Here are the common methods for reversing NumPy arrays:

###  Reversing a 1D Array

In [13]:
import numpy as np
arr_1D = np.array([1,2,3,4,5])
reversed_arr_1D = arr_1D[::-1]
print("Original 1D array:", arr_1D)
print("Reversed 1D array:", reversed_arr_1D)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


### Reversing a 2D Array

In [17]:
arr_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
reversed_rows = arr_2D[::-1, :]
print("Original 2D array:\n", arr_2D)
print("Reversed 2D array:\n", reversed_rows)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [19]:
# Reversing Columns (along axis 1):

reversed_columns = arr_2D[:, ::-1]
print("Columns reversed 2D array:\n",reversed_columns)

Columns reversed 2D array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [20]:
# Reversing Both Rows and Columns:

reversed_columns = arr_2D[::-1, ::-1]
print("Rows an Columns reversed 2D array:\n", reversed_columns)

Rows an Columns reversed 2D array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [22]:
#Q4). How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#A4). In NumPy, the data type of the elements in an array can be determined using the dtype attribute of the array. The dtype attribute provides information about the type of the elements stored in the array, such as whether they are integers, floats, strings, etc., and their respective sizes.
#Example of how to determine a datatype in a Numpy array:

arr_int = np.array([1, 2, 3])
arr_float = np.array([1.50, 2.50, 3.50])
arr_string = np.array(["Apple", "Banana", "Mangoe"])
print("The data type of arr_int is:", arr_int.dtype)
print("The data type of arr_float is:", arr_float.dtype)
print("The data type of arr_string is:", arr_string.dtype)

The data type of arr_int is: int64
The data type of arr_float is: float64
The data type of arr_string is: <U6


### Importance of Data Types in Memory Management and Performance


In [23]:
#1 Memory Management:
# Efficient Storage: The data type determines the amount of memory required to store each element in an array. For example, a float64 takes 64 bits (8 bytes) per element, while a float32 takes 32 bits (4 bytes). Choosing an appropriate data type can help in optimizing memory usage, especially when working with large datasets.
# Fixed Size: NumPy arrays are homogeneous, meaning all elements are of the same data type. This allows for contiguous memory allocation, which is more efficient in terms of memory access and can reduce memory fragmentation.

#2 Performance:
# Speed of Computation: The choice of data type can significantly affect the speed of computations. Operations on arrays with simpler data types (like int32 or float32) are generally faster than operations on arrays with more complex data types (like float64 or object types). This is because simpler data types require fewer CPU cycles to process.
# Hardware Optimization: NumPy is optimized for numerical operations, and choosing the correct data type can leverage hardware-specific optimizations. For example, using 32-bit integers or floats can take advantage of SIMD (Single Instruction, Multiple Data) instructions on modern CPUs, which can process multiple data points in parallel.

#3 Precision:
# The data type also affects the precision of numerical calculations. For example, float32 has less precision than float64. While using float32 might save memory and improve speed, it could lead to precision errors in calculations, which is crucial in applications requiring high accuracy.

In [ ]:
#Q5). Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#A5). ndarray (short for N-dimensional array) is the core data structure in NumPy, which is a powerful library for numerical computing in Python. An ndarray can represent a multidimensional, homogeneous array of fixed-size items. This means that all elements in an ndarray have the same data type and are stored in contiguous memory locations, making operations on these arrays efficient.

### Key Features of 'ndarray'

In [24]:
#Homogeneous Data Type:
# All elements in an ndarray must be of the same data type (e.g., all integers, all floats, etc.). This uniformity allows NumPy to use specialized, efficient algorithms for array operations.

#M ultidimensional:
# ndarray can have multiple dimensions, making it suitable for representing matrices, tensors, or any n-dimensional grid of data. The number of dimensions is known as the array's rank, and the size of the array along each dimension is known as its shape.

# Efficient Memory Storage:
# Elements in an ndarray are stored in contiguous blocks of memory, enabling efficient access and manipulation. This layout reduces memory overhead and allows NumPy to leverage low-level optimizations.

# Element-wise Operations:
# NumPy supports vectorized operations, allowing element-wise arithmetic, logical, and other operations to be performed efficiently without explicit loops. This capability leads to more concise and faster code.

# Broadcasting:
# NumPy arrays can perform operations with arrays of different shapes through a mechanism called broadcasting. This allows for implicit expansion of smaller arrays to match the shape of larger ones during operations, without physically copying data.

### Differences Between ndarray and Standard Python Lists


In [25]:
#1) Data Type Uniformity:
# ndarray: All elements must be of the same data type, specified by the dtype attribute.
# Python Lists: Can contain elements of different data types (heterogeneous).

#2). Memory Efficiency:
# ndarray: Uses contiguous memory blocks for storage, leading to efficient memory usage and fast access times.
# Python Lists: Store elements as references to objects, leading to potential memory overhead and slower access times.

#3). Performance:
# ndarray: Operations are implemented in C and are highly optimized, making them much faster for numerical computations.
# Python Lists: Operations are implemented in Python and involve more overhead, making them slower for numerical tasks.

#4). Multidimensional Support:
# ndarray: Natively supports multiple dimensions (e.g., 2D arrays for matrices, 3D arrays for tensors).
# Python Lists: Can represent multidimensional data using nested lists, but this is less efficient and more cumbersome.

#5). Vectorized Operations:
# ndarray: Supports vectorized operations, enabling concise and efficient element-wise computations.
# Python Lists: Require explicit loops for element-wise operations, which are less efficient.

In [26]:
#Q6). Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#A6). NumPy arrays (ndarrays) offer significant performance benefits over Python lists, especially for large-scale numerical operations. These advantages stem from several key features and optimizations inherent in NumPy's design:

#1). Memory Efficiency
# Homogeneous Data Types: NumPy arrays require that all elements have the same data type, allowing them to be stored in contiguous memory blocks. This uniformity reduces memory overhead and increases the density of data storage.
# Fixed Size: The size of each element is known and fixed, leading to more efficient memory allocation compared to Python lists, which can store elements of varying sizes.

#2). Speed of Computation
# Vectorization: NumPy supports vectorized operations, allowing the application of a function to entire arrays without explicit loops. This leads to significant speedups because operations are implemented at the compiled C level, avoiding the overhead of Python loops.
# SIMD and Low-level Optimization: NumPy takes advantage of SIMD (Single Instruction, Multiple Data) and other low-level optimizations available on modern processors. This allows multiple data points to be processed simultaneously, further accelerating computations.

#3). Efficient Broadcasting
# Broadcasting: NumPy's broadcasting mechanism allows operations on arrays of different shapes without copying data. This can greatly reduce memory usage and increase computational efficiency, as it avoids the creation of intermediate arrays.

#4). Reduced Overhead
# Memory Allocation: NumPy arrays have a single block of memory for data storage, whereas Python lists are arrays of pointers to objects, leading to higher memory consumption and slower access due to indirection.
# Optimized Operations: Many operations in NumPy, such as element-wise arithmetic, aggregation (e.g., sum, mean), and linear algebra, are implemented in compiled C and Fortran. This allows them to run much faster than equivalent operations in pure Python.

#5). Use of Specialized Algorithms
# Specialized Functions: NumPy provides a wide range of optimized functions for mathematical operations, statistical analysis, and linear algebra. These functions are often faster and more numerically stable than manually implemented equivalents in Python.

In [ ]:
#Q7). Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#A7). In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They are useful for combining arrays in different dimensions.

### vstack() Function

In [27]:
#The vstack() function stacks arrays along the vertical axis (rows). It requires the arrays to have the same number of columns (second dimension) but can have a different number of rows.
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_vstack = np.vstack((array1, array2))
print("array1:", array1)
print("array2:", array2)
print("vstack result:\n", result_vstack)

array1: [1 2 3]
array2: [4 5 6]
vstack result:
 [[1 2 3]
 [4 5 6]]


### hstack() Function

In [30]:
# The hstack() function stacks arrays along the horizontal axis (columns). It requires the arrays to have the same number of rows (first dimension) but can have a different number of columns.
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result_hstack = np.hstack((array1, array2))
print("array1:", array1)
print("array2:", array2)
print("hstack result:", result_hstack)

array1: [1 2 3]
array2: [4 5 6]
hstack result: [1 2 3 4 5 6]


In [31]:
#Q8). Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#A8). In NumPy, the fliplr() and flipud() functions are used to flip arrays along specific axes. These functions are helpful for reversing the order of elements along the horizontal or vertical axis, respectively.

### fliplr() Function

In [32]:
# The fliplr() function flips an array from left to right, i.e., along the horizontal axis. It requires the input array to have at least two dimensions (2D or higher).
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
flipped_lr = np.fliplr(arr)
print("Original array:\n", arr)
print("fliplr result:\n", flipped_lr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
fliplr result:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


### flipud() Function

In [34]:
# The flipud() function flips an array upside down, i.e., along the vertical axis. It can be used on arrays of any dimensionality, including 1D arrays.
flip_ud = np.flipud(arr)
print("Original array:\n", arr)
print("flipud result:\n", flip_ud)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
flipud result:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [36]:
#Q9). Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#A9). The array_split() function in NumPy is used to split an array into multiple sub-arrays along a specified axis. Unlike the split() function, which requires the array to be evenly divisible into the specified number of splits, array_split() can handle cases where the array cannot be split evenly. It ensures that the resulting sub-arrays have as balanced a shape as possible, distributing the remainder elements among the sub-arrays.

# Example 1: Uneven Split with Integer Sections
arr = np.array([1,2,3,4,5,6,7])
split_arrs = np.array_split(arr,3)
for i, sub_array in enumerate(split_arrs):
    print(f"Sub-array {i}: {sub_array}:")

Sub-array 0: [1 2 3]:
Sub-array 1: [4 5]:
Sub-array 2: [6 7]:


In [38]:
# Example 2: Specifying Split Indices
arr = np.array([1,2,3,4,5,6,7])
split_arrs = np.array_split(arr, [2,5])
for i, sub_array in enumerate(split_arrs):
    print(f"Sub-array {i}: {sub_array}")

Sub-array 0: [1 2]
Sub-array 1: [3 4 5]
Sub-array 2: [6 7]


In [40]:
# Example 3: Splitting Along a Specific Axis
arr_2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
split_arrs_2D = np.array_split(arr_2D, 2, axis = 1)
for i, sub_array in enumerate(split_arrs_2D):
    print(f"Sub-array {i}:\n{sub_array}")


Sub-array 0:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Sub-array 1:
[[ 3  4]
 [ 7  8]
 [11 12]]


In [41]:
#10). Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#10). Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency of array operations. They enable concise, readable code and improve performance by leveraging optimized, low-level implementations.

### Vectorization

In [ ]:
# Vectorization refers to the process of replacing explicit loops in the code with array expressions. In NumPy, many operations are vectorized, meaning they operate on entire arrays rather than individual elements. This is achieved through highly optimized C and Fortran routines, allowing NumPy to execute these operations much faster than equivalent Python loops.

In [42]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a+b
print(c)

[11 22 33 44]


### Broadcasting

In [43]:
# Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes in a way that would normally be incompatible. When performing operations between two arrays of different shapes, NumPy automatically "broadcasts" the smaller array across the larger array so that they have compatible shapes.

In [46]:
a = np.array([1,2,3])
b = np.array([[10], [20], [30]])
result = a+b
print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Contribution to Efficient Array Operations

In [47]:
# Memory Efficiency: Broadcasting avoids creating unnecessary intermediate arrays, saving memory. It performs operations in place where possible, reducing memory overhead.
# Speed: Vectorized operations and broadcasting enable NumPy to take advantage of low-level optimizations and parallelism. This results in significant speedups compared to element-wise operations implemented with Python loops.
# Ease of Use: Both concepts allow for writing concise and readable code. Complex operations can often be expressed in a single line, making the code easier to understand and maintain.

### Practical Example: Vectorization and Broadcasting Combined

In [49]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])
result = a*b
print(result)

[[ 1  4  9]
 [ 4 10 18]]


### Practical Questions:

In [ ]:
#Q1). Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np
arr = np.random.randint(1,101, size = (3,3))
arr

array([[86, 10, 48],
       [ 4, 40, 26],
       [14, 44, 88]])

In [4]:
# Interchanging its rows and columns
transposed_array = arr.T
transposed_array

array([[86,  4, 14],
       [10, 40, 44],
       [48, 26, 88]])

In [6]:
#Q2). Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

#A2). 
arr1D = np.arange(1,11)
arr1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Reshaping it into a 2x5 array
array_two_by_five = arr1D.reshape(2,5)
array_two_by_five

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# Reshaping it into a 5x2 array
array_five_by_two = arr1D.reshape(5,2)
array_five_by_two

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
# Create a 4x4 NumPy array with random float values
array = np.random.random((4, 4))

# Add a border of zeros around the array to make it 6x6
padded_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

# Print the results
print("Original Array:\n", array)
print("Padded Array:\n", padded_array)

Original Array:
 [[0.45441444 0.23680648 0.53436054 0.26372414]
 [0.94709153 0.77899644 0.98830904 0.54516069]
 [0.42565738 0.44387572 0.15225295 0.59096235]
 [0.88781453 0.25891758 0.61082964 0.73228972]]
Padded Array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.45441444 0.23680648 0.53436054 0.26372414 0.        ]
 [0.         0.94709153 0.77899644 0.98830904 0.54516069 0.        ]
 [0.         0.42565738 0.44387572 0.15225295 0.59096235 0.        ]
 [0.         0.88781453 0.25891758 0.61082964 0.73228972 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [26]:
#Q3). Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

#A3). 
original_array = np.random.rand(4, 4)
padded_array = np.pad(original_array, pad_width = 1, m

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.30048247, 0.99949461, 0.33227699, 0.7387629 ,
        0.        ],
       [0.        , 0.87981322, 0.39433008, 0.3393411 , 0.87403425,
        0.        ],
       [0.        , 0.92999852, 0.49678769, 0.00346318, 0.11199717,
        0.        ],
       [0.        , 0.40971935, 0.93941588, 0.76433348, 0.00686203,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [28]:
#Q4) . Using NumPy, create an array of integers from 10 to 60 with a step of 5

#A4).
array = np.arange(10,61,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [30]:
#Q5). Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

#A5).
array = np.array(['python', 'numpy', 'pandas'])
upperchase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
print("original array:", array)
print("Uppercase:", upperchase_array)
print("Lowercase:", lowercase_array)
print("Titlecase:", titlecase_array)

original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']


In [31]:
#Q6). Generate a NumPy array of words. Insert a space between each character of every word in the array.

#A6).
array_words = np.array(['hello', 'world', 'numpy'])
spaced_array = np.char.join(' ', array_words)
print("Original array:", array_words)
print("Spaced array:", spaced_array)
                        

Original array: ['hello' 'world' 'numpy']
Spaced array: ['h e l l o' 'w o r l d' 'n u m p y']


In [33]:
#Q7). Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

#A7).
array1 = np.array([[1,2,3], [4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2\

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("subraction:\n", subtraction)
print("multiplication:\n", multiplication)
print("Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
subraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [36]:
#Q8). Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

#A8).
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [37]:
#Q9). Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

#A9).
random_array = np.random.randint(0,1001, size = 100)
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <=n:
        if n % i == 0 or n % (1 + 2) == 0:
            return False
        i += 6
    return True
prime_number = [num for num in random_array if is_prime(num)]
print("Random Array:\n", random_array)
print("Prime Number:\n", prime_number) 

Random Array:
 [749 512 257 472 798 748 226 107 270 488 770 924 233 147 896 334 905 618
 417 978 741 193 921 631 803 350 325 927 567 998 242 248 530 139 457 877
 165 557 754 522 601 925 765 537 704 312  49  11 868 907   7 974 456  99
 318 114 972   9 993 868 970 923 394 309 895 820 393 903 998 560 568 233
 752 911 141 503 968 103 108 513 105 574 801 868 387 192 274 479 698 979
 750 288 978 888 396 777 104  60 719 572]
Prime Number:
 [749, 257, 107, 233, 193, 631, 139, 457, 877, 557, 601, 49, 11, 907, 7, 923, 233, 911, 503, 103, 479, 719]


In [40]:
#Q10). Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

#A10).
daily_temperature = np.random.randint(0,35, size = 28)
weekly_temperature = daily_temperature.reshape(4,7)
weekly_average = np.mean(weekly_temperature, axis = 1)
print("Daily Temperatures:\n", daily_temperature)
print("Weekly Temperatures:\n", weekly_temperature)
print("Weekly Average:\n", weekly_average)

Daily Temperatures:
 [24  7 17 28 26 25 23 11 30 13 24 23 16  7  7 13 13 18  4 28  7 33 16  8
 12 26 13 11]
Weekly Temperatures:
 [[24  7 17 28 26 25 23]
 [11 30 13 24 23 16  7]
 [ 7 13 13 18  4 28  7]
 [33 16  8 12 26 13 11]]
Weekly Average:
 [21.42857143 17.71428571 12.85714286 17.        ]
